### ISSUE TITLE
Why multipart.DataFields use map[string]string to contain the request form?

### ISSUE THREAD

**Issue by er1iang** [h2non/gentleman#22]
Normally, a form key only  has single value, but it's also right with multiple values .

Why not use `url.Values` ?

**Comment by er1iang** [comment]
If we use `Body` or `BodyString` method to make 1:n key-value pair, we need define the proper Content-Type header representing the real content MIME type.

**Comment by tomas-fp** [comment]
Clearly, this is an interface limitation. It should be `map[string][]string`, such as `url.Values`:
https://golang.org/pkg/net/url/#Values

If you want a fast fix, would you mind providing a PR? I will merge it asap!

**Comment by er1iang** [comment]
I'm still reviewing and testing the code. I will try to contribute code later.

**Comment by h2non** [comment]
I had a few time tonight to fix this. See: https://github.com/h2non/gentleman/commit/b8321b809b88815e5d58c56cc0fdf376f84f0640

The fix will be shipped in `gentleman@v1.0.3` soon.

**Comment by h2non** [comment]
Fix was shipped in `gentleman@v1.0.3`. You can upgrade it running: 
```bash
go get -u gopkg.in/h2non/gentleman.v1
```
